// ============================================================
// DeployIQ — features.js  (10 new features)
// ============================================================

// ── F1: Export Report (PDF / Markdown) ──────────────────────
function exportMarkdown() {
  if (!currentDiagnosis) return toast('Run a diagnosis first', 'error');
  const d = currentDiagnosis;
  const md = `# DeployIQ Diagnosis Report\n\n**Failed Stage:** ${d.stage}\n**Category:** ${d.category}\n**Confidence:** ${d.confidence}\n**Fix Time:** ${d.fixTime}\n**Platform:** ${d.platform || '—'}\n\n## Root Cause\n${d.rootCause}\n\n## Why It Broke\n${(d.technical||'').replace(/<[^>]+>/g,'')}\n\n## Fix Steps\n${(d.steps||[]).map((s,i)=>`${i+1}. **${s.label}**\n\`\`\`\n${s.cmd}\n\`\`\``).join('\n\n')}\n\n## Prevention\n${(d.prevention||[]).map(p=>`- ${p}`).join('\n')}\n\n---\n*Generated by DeployIQ ${new Date().toLocaleString()}*`;
  const blob = new Blob([md], {type:'text/markdown'});
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), {href:url, download:'deployiq-report.md'});
  a.click(); URL.revokeObjectURL(url);
  toast('Markdown report downloaded ✓', 'success');
}

function exportPDF() {
  if (!currentDiagnosis) return toast('Run a diagnosis first', 'error');
  window.print();
  toast('Use browser Print → Save as PDF', 'success');
}

document.getElementById('export-md-btn').addEventListener('click', exportMarkdown);
document.getElementById('export-pdf-btn').addEventListener('click', exportPDF);

// ── F2: Shareable Link ───────────────────────────────────────
function generateShareLink() {
  if (!currentDiagnosis) return toast('Run a diagnosis first', 'error');
  const d = currentDiagnosis;
  const payload = btoa(unescape(encodeURIComponent(JSON.stringify({
    stage: d.stage, category: d.category, confidence: d.confidence,
    fixTime: d.fixTime, platform: d.platform, rootCause: d.rootCause,
    prevention: d.prevention, ts: new Date().toISOString()
  }))));
  const url = `${location.origin}${location.pathname}?share=${payload}`;
  navigator.clipboard.writeText(url).then(() => toast('Share link copied to clipboard ✓', 'success'));
  document.getElementById('share-link-input').value = url;
  document.getElementById('share-modal').classList.add('open');
}

function loadSharedDiagnosis() {
  const params = new URLSearchParams(location.search);
  const s = params.get('share');
  if (!s) return;
  try {
    const d = JSON.parse(decodeURIComponent(escape(atob(s))));
    currentDiagnosis = d;
    renderOutput(d);
    document.getElementById('output-section').style.display = '';
    toast('Shared diagnosis loaded ✓', 'success');
  } catch(e) {}
}

document.getElementById('share-btn').addEventListener('click', generateShareLink);
document.getElementById('share-modal-close').addEventListener('click', () => document.getElementById('share-modal').classList.remove('open'));
document.getElementById('share-copy-btn').addEventListener('click', () => {
  navigator.clipboard.writeText(document.getElementById('share-link-input').value);
  toast('Copied!', 'success');
});
loadSharedDiagnosis();

// ── F3: Slack / Discord Notification ────────────────────────
document.getElementById('notify-btn').addEventListener('click', () => {
  document.getElementById('notify-modal').classList.add('open');
});
document.getElementById('notify-modal-close').addEventListener('click', () => document.getElementById('notify-modal').classList.remove('open'));

document.getElementById('send-notify-btn').addEventListener('click', async () => {
  if (!currentDiagnosis) return toast('Run a diagnosis first', 'error');
  const webhook = document.getElementById('webhook-url-input').value.trim();
  if (!webhook) return toast('Enter a webhook URL', 'error');
  const d = currentDiagnosis;
  const isSlack   = webhook.includes('hooks.slack.com');
  const isDiscord = webhook.includes('discord.com');
  const text = `*DeployIQ Diagnosis*\n*Stage:* ${d.stage}\n*Category:* ${d.category}\n*Confidence:* ${d.confidence}\n*Root Cause:* ${d.rootCause}\n*Fix:* ${d.steps?.[0]?.label || '—'}`;
  const body = isDiscord
    ? JSON.stringify({content: text})
    : JSON.stringify({text});
  try {
    await fetch(webhook, {method:'POST', headers:{'Content-Type':'application/json'}, body});
    toast('Notification sent ✓', 'success');
    document.getElementById('notify-modal').classList.remove('open');
    localStorage.setItem('deployiq_webhook', webhook);
  } catch(e) {
    toast('Failed — check webhook URL & CORS', 'error');
  }
});

// Pre-fill saved webhook
const savedHook = localStorage.getItem('deployiq_webhook');
if (savedHook) document.getElementById('webhook-url-input').value = savedHook;

// ── F4: File Upload Button ───────────────────────────────────
document.getElementById('file-upload-btn').addEventListener('click', () => {
  document.getElementById('file-upload-input').click();
});
document.getElementById('file-upload-input').addEventListener('change', e => {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = ev => {
    document.getElementById('log-input').value = ev.target.result;
    document.getElementById('log-input').dispatchEvent(new Event('input'));
    toast(`Loaded: ${file.name}`, 'success');
  };
  reader.readAsText(file);
  e.target.value = '';
});

// ── F5: Re-run & Compare ─────────────────────────────────────
let _lastDiagnosis = null;

function saveLastDiagnosis(d) {
  _lastDiagnosis = JSON.parse(JSON.stringify(d));
}

function showCompare(prev, curr) {
  const modal = document.getElementById('compare-modal');
  const body  = document.getElementById('compare-body');
  const fields = ['stage','category','confidence','fixTime','rootCause'];
  body.innerHTML = fields.map(f => {
    const pv = (prev[f]||'—'), cv = (curr[f]||'—');
    const changed = pv !== cv;
    return `<div class="compare-row ${changed?'changed':''}">
      <div class="compare-field">${f}</div>
      <div class="compare-val old">${escHtml(String(pv))}</div>
      <div class="compare-arrow">→</div>
      <div class="compare-val new">${escHtml(String(cv))}</div>
    </div>`;
  }).join('');
  modal.classList.add('open');
}

document.getElementById('rerun-btn').addEventListener('click', async () => {
  if (!currentDiagnosis) return toast('Run a diagnosis first', 'error');
  saveLastDiagnosis(currentDiagnosis);
  await window.runDiagnosis();
  if (_lastDiagnosis) showCompare(_lastDiagnosis, currentDiagnosis);
});
document.getElementById('compare-modal-close').addEventListener('click', () => document.getElementById('compare-modal').classList.remove('open'));

// Hook into runDiagnosis to save last
const _origSaveHistory = saveToHistory;
const _patchedSave = function(d, logs) {
  _origSaveHistory(d, logs);
};

// ── F6: Tag & Organize History ────────────────────────────────
function addTagToEntry(id, tag) {
  const entry = history.find(e => e.id === id);
  if (!entry) return;
  entry.tags = entry.tags || [];
  if (!entry.tags.includes(tag)) entry.tags.push(tag);
  localStorage.setItem('deployiq_history', JSON.stringify(history));
  renderHistory();
  toast(`Tag "${tag}" added`, 'success');
}

function removeTagFromEntry(id, tag) {
  const entry = history.find(e => e.id === id);
  if (!entry || !entry.tags) return;
  entry.tags = entry.tags.filter(t => t !== tag);
  localStorage.setItem('deployiq_history', JSON.stringify(history));
  renderHistory();
}

// Patch renderHistory to show tags and add-tag button
const _origRenderHistory = renderHistory;
window.renderHistoryWithTags = function() {
  _origRenderHistory();
  document.querySelectorAll('.history-item').forEach(item => {
    const id = parseInt(item.dataset.id);
    const entry = history.find(e => e.id === id);
    if (!entry) return;
    const tags = entry.tags || [];
    let tagRow = item.querySelector('.history-tags');
    if (!tagRow) {
      tagRow = document.createElement('div');
      tagRow.className = 'history-tags';
      item.querySelector('.history-info').appendChild(tagRow);
    }
    tagRow.innerHTML = tags.map(t =>
      `<span class="htag" data-id="${id}" data-tag="${escHtml(t)}">${escHtml(t)} <span class="htag-remove">×</span></span>`
    ).join('') +
      `<button class="htag-add" data-id="${id}">+ tag</button>`;
  });

  document.querySelectorAll('.htag-remove').forEach(btn => {
    btn.addEventListener('click', e => {
      e.stopPropagation();
      const span = btn.closest('.htag');
      removeTagFromEntry(parseInt(span.dataset.id), span.dataset.tag);
    });
  });

  document.querySelectorAll('.htag-add').forEach(btn => {
    btn.addEventListener('click', e => {
      e.stopPropagation();
      const id = parseInt(btn.dataset.id);
      const tag = prompt('Enter tag name:');
      if (tag && tag.trim()) addTagToEntry(id, tag.trim());
    });
  });
};

// Override switchSection to use patched renderHistory
const _origSwitchSection = switchSection;
window.switchSection = function(name) {
  _origSwitchSection(name);
  if (name === 'history') setTimeout(window.renderHistoryWithTags, 50);
};
document.querySelectorAll('.nav-link').forEach(link => {
  link.addEventListener('click', e => {
    e.preventDefault();
    const target = link.getAttribute('href').replace('#','');
    window.switchSection(target);
  });
});

// ── F7: Multi-language (i18n) ────────────────────────────────
const LANG_META = {
  en: { flag:'🌐', name:'English'  },
  es: { flag:'🇪🇸', name:'Español'  },
  fr: { flag:'🇫🇷', name:'Français' },
  de: { flag:'🇩🇪', name:'Deutsch'  },
  hi: { flag:'🇮🇳', name:'हिन्दी'   }
};
const LANGS = {
  en: { diagnose:'Diagnose', history:'History', analytics:'Analytics', docs:'Docs', runDiag:'Run Diagnosis', placeholder:'Paste your CI/CD logs here…' },
  es: { diagnose:'Diagnosticar', history:'Historial', analytics:'Analítica', docs:'Docs', runDiag:'Ejecutar Diagnóstico', placeholder:'Pega tus logs de CI/CD aquí…' },
  fr: { diagnose:'Diagnostiquer', history:'Historique', analytics:'Analytique', docs:'Docs', runDiag:'Lancer Diagnostic', placeholder:'Collez vos logs CI/CD ici…' },
  de: { diagnose:'Diagnostizieren', history:'Verlauf', analytics:'Analytik', docs:'Docs', runDiag:'Diagnose starten', placeholder:'CI/CD-Logs hier einfügen…' },
  hi: { diagnose:'डायगनोज़', history:'इतिहास', analytics:'विश्लेषण', docs:'डॉक्स', runDiag:'डायगनोसिस चलाएं', placeholder:'अपने CI/CD लॉग यहाँ पेस्ट करें…' }
};

let currentLang = localStorage.getItem('deployiq_lang') || 'en';

function applyLang(code) {
  const t    = LANGS[code] || LANGS.en;
  const meta = LANG_META[code] || LANG_META.en;
  currentLang = code;
  localStorage.setItem('deployiq_lang', code);
  document.getElementById('nav-diagnose').textContent   = t.diagnose;
  document.getElementById('nav-history').textContent    = t.history;
  document.getElementById('nav-analytics').textContent  = '📊 ' + t.analytics;
  document.getElementById('nav-docs').textContent       = t.docs;
  const btn = document.getElementById('diagnose-btn');
  if (btn) btn.querySelector('.btn-content').lastChild.textContent = ' ' + t.runDiag;
  document.getElementById('log-input').placeholder = t.placeholder;
  // Update trigger
  const flagEl = document.getElementById('lang-flag');
  const codeEl = document.getElementById('lang-code');
  if (flagEl) flagEl.textContent = meta.flag;
  if (codeEl) codeEl.textContent = code.toUpperCase();
  // Mark active option
  document.querySelectorAll('.lang-option').forEach(opt =>
    opt.classList.toggle('active', opt.dataset.lang === code)
  );
}

// Custom dropdown wiring
const _langDrop    = document.getElementById('lang-dropdown');
const _langTrigger = document.getElementById('lang-trigger');
if (_langTrigger) {
  _langTrigger.addEventListener('click', e => { e.stopPropagation(); _langDrop.classList.toggle('open'); });
}
document.addEventListener('click', () => _langDrop && _langDrop.classList.remove('open'));
document.querySelectorAll('.lang-option').forEach(opt => {
  opt.addEventListener('click', () => { applyLang(opt.dataset.lang); _langDrop.classList.remove('open'); });
});

applyLang(currentLang);

// ── F8: Weekly Report (UI + download) ────────────────────────
document.getElementById('weekly-report-btn').addEventListener('click', () => {
  const weekAgo = Date.now() - 7*24*60*60*1000;
  const week = history.filter(e => new Date(e.ts).getTime() > weekAgo);
  const total = week.length;
  const cats  = {};
  week.forEach(e => { const c = (e.category||'Unknown').split(':').slice(-1)[0].trim(); cats[c]=(cats[c]||0)+1; });
  const topCat = Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];
  const md = `# DeployIQ Weekly Report\n**Period:** ${new Date(weekAgo).toLocaleDateString()} – ${new Date().toLocaleDateString()}\n\n## Summary\n- **Total Diagnoses:** ${total}\n- **Top Failure Category:** ${topCat?topCat[0]+' ('+topCat[1]+')':'N/A'}\n- **High Confidence:** ${week.filter(e=>e.confidence==='HIGH').length}\n\n## All This Week\n${week.map(e=>`- **${e.stage}** — ${(e.category||'').split(':').slice(-1)[0].trim()} (${e.confidence}) — ${new Date(e.ts).toLocaleDateString()}`).join('\n')||'No diagnoses this week.'}\n\n---\n*Generated by DeployIQ ${new Date().toLocaleString()}*`;
  const blob = new Blob([md], {type:'text/markdown'});
  const a = Object.assign(document.createElement('a'), {href: URL.createObjectURL(blob), download:'deployiq-weekly-report.md'});
  a.click();
  toast('Weekly report downloaded ✓', 'success');
});

// ── F9: Custom Themes ─────────────────────────────────────────
const THEMES = {
  default: { primary:'#3b82f6', accent:'#f472b6', karke:'#7c3aed', bg:'#03020a' },
  ocean:   { primary:'#06b6d4', accent:'#67e8f9', karke:'#0284c7', bg:'#020c14' },
  sunset:  { primary:'#f97316', accent:'#fbbf24', karke:'#dc2626', bg:'#0f0500' },
  forest:  { primary:'#22c55e', accent:'#86efac', karke:'#16a34a', bg:'#010f05' },
  rose:    { primary:'#ec4899', accent:'#f9a8d4', karke:'#be185d', bg:'#0f0208' },
  mono:    { primary:'#94a3b8', accent:'#e2e8f0', karke:'#64748b', bg:'#020408' }
};

function applyTheme(name) {
  const t = THEMES[name] || THEMES.default;
  const r = document.documentElement.style;
  r.setProperty('--primary', t.primary);
  r.setProperty('--accent',  t.accent);
  r.setProperty('--karke-mid', t.karke);
  r.setProperty('--bg', t.bg);
  r.setProperty('--primary-glow', t.primary + '55');
  r.setProperty('--accent-glow',  t.accent  + '44');
  localStorage.setItem('deployiq_theme_name', name);
  document.querySelectorAll('.theme-chip').forEach(c => c.classList.toggle('active', c.dataset.theme === name));
  toast(`Theme: ${name} ✓`, 'success');
}

const savedTheme = localStorage.getItem('deployiq_theme_name');
if (savedTheme) applyTheme(savedTheme);

document.querySelectorAll('.theme-chip').forEach(chip => {
  chip.addEventListener('click', () => applyTheme(chip.dataset.theme));
});

document.getElementById('theme-modal-btn').addEventListener('click', () => {
  document.getElementById('theme-modal').classList.add('open');
});
document.getElementById('theme-modal-close').addEventListener('click', () => {
  document.getElementById('theme-modal').classList.remove('open');
});

// ── F10: Keyboard Shortcuts Panel ────────────────────────────
const SHORTCUTS = [
  { keys: ['Ctrl','Enter'],  desc: 'Run Diagnosis' },
  { keys: ['Ctrl','K'],      desc: 'Focus log input' },
  { keys: ['Ctrl','/'],      desc: 'Show shortcuts' },
  { keys: ['Ctrl','E'],      desc: 'Export report' },
  { keys: ['Ctrl','S'],      desc: 'Share link' },
  { keys: ['Ctrl','H'],      desc: 'Go to History' },
  { keys: ['Ctrl','D'],      desc: 'Go to Diagnose' },
  { keys: ['Escape'],        desc: 'Close modals' },
];

function showShortcuts() {
  document.getElementById('shortcuts-modal').classList.add('open');
}
function hideShortcuts() {
  document.getElementById('shortcuts-modal').classList.remove('open');
}

document.getElementById('shortcuts-modal-close').addEventListener('click', hideShortcuts);
document.getElementById('shortcuts-btn').addEventListener('click', showShortcuts);

document.getElementById('shortcuts-list').innerHTML = SHORTCUTS.map(s =>
  `<div class="shortcut-row">
    <div class="shortcut-keys">${s.keys.map(k=>`<kbd>${k}</kbd>`).join('+')}</div>
    <div class="shortcut-desc">${s.desc}</div>
  </div>`
).join('');

// Global keyboard shortcuts
document.addEventListener('keydown', e => {
  const ctrl = e.ctrlKey || e.metaKey;
  if (ctrl && e.key === '/') { e.preventDefault(); showShortcuts(); }
  if (ctrl && e.key === 'k') { e.preventDefault(); document.getElementById('log-input').focus(); window.switchSection('diagnose'); }
  if (ctrl && e.key === 'e') { e.preventDefault(); exportMarkdown(); }
  if (ctrl && e.key === 's') { e.preventDefault(); generateShareLink(); }
  if (ctrl && e.key === 'h') { e.preventDefault(); window.switchSection('history'); }
  if (ctrl && e.key === 'd') { e.preventDefault(); window.switchSection('diagnose'); }
  if (e.key === 'Escape') {
    document.querySelectorAll('.modal-overlay.open, .feature-modal.open').forEach(m => m.classList.remove('open'));
  }
});

// ── Close modals on overlay click ────────────────────────────
document.querySelectorAll('.feature-modal').forEach(modal => {
  modal.addEventListener('click', e => {
    if (e.target === modal) modal.classList.remove('open');
  });
});
