"""
generate_config.py
──────────────────
Reads DeployIQ/.env and writes public/config.js so the
static HTML frontend can access SUPABASE_URL and SUPABASE_ANON_KEY.

Usage:
    python generate_config.py

Run this once after filling in your real values in .env.
config.js is in .gitignore — never committed.
"""

import os
import re
import sys

ENV_FILE    = os.path.join(os.path.dirname(__file__), ".env")
CONFIG_FILE = os.path.join(os.path.dirname(__file__), "config.js")

# Keys that are safe to expose in the browser
FRONTEND_KEYS = [
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
]


def parse_env(path: str) -> dict[str, str]:
    """Parse a .env file, stripping comments and inline comments."""
    result = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            # Skip blank lines and full-line comments
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, raw_val = line.partition("=")
            key = key.strip()
            # Strip inline comment (e.g.  "eyJ...  # safe to expose")
            val = re.sub(r"\s+#.*$", "", raw_val).strip()
            result[key] = val
    return result


def is_placeholder(val: str) -> bool:
    """Return True if the value still looks like a placeholder."""
    placeholder_patterns = [
        r"^eyJ\.\.\.",          # eyJ...
        r"^https://xxxx",       # https://xxxx...
        r"^sk-\.\.\.",          # sk-...
        r"^sk-ant-\.\.\.",      # sk-ant-...
        r"^xoxb-\.\.\.",        # Slack placeholder
        r"^\.\.\.",             # just ...
        r"^your-",              # your-random-secret
    ]
    return any(re.match(p, val) for p in placeholder_patterns)


def generate(env: dict[str, str]) -> str:
    """Build the config.js content."""
    lines = [
        "// config.js — AUTO-GENERATED by generate_config.py",
        "// DO NOT edit manually. DO NOT commit to git.",
        "// Re-run:  python generate_config.py",
        "",
    ]

    warnings = []
    for key in FRONTEND_KEYS:
        val = env.get(key, "")
        if not val or is_placeholder(val):
            warnings.append(key)
            val = ""   # expose empty string so app falls back to demo mode
        lines.append(f'window.{key} = "{val}";')

    lines.append("")

    if warnings:
        print("\nWARNING: The following keys still have placeholder values in .env:")
        for w in warnings:
            print(f"   - {w}")
        print("   The frontend will fall back to Demo Mode until you fill them in.\n")
    else:
        print("\nSUCCESS: config.js written — real Supabase credentials wired in.\n")

    return "\n".join(lines)


def main():
    if not os.path.exists(ENV_FILE):
        print(f"ERROR: .env not found at: {ENV_FILE}")
        sys.exit(1)

    env = parse_env(ENV_FILE)
    content = generate(env)

    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"   config.js -> {CONFIG_FILE}")


if __name__ == "__main__":
    main()
