"""
generate_config.py
──────────────────
Writes config.js so the static HTML frontend can access SUPABASE_URL
and SUPABASE_ANON_KEY.

Priority:
  1. System environment variables  ← Vercel injects these at build time
  2. Local .env file               ← Used in local dev

Usage:
    python generate_config.py

config.js is in .gitignore — never committed.
"""

import os
import re
import sys

ENV_FILE    = os.path.join(os.path.dirname(__file__), ".env")
CONFIG_FILE = os.path.join(os.path.dirname(__file__), "config.js")

# Keys that are safe to expose in the browser
FRONTEND_KEYS = [
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
]


def parse_env_file(path: str) -> dict[str, str]:
    """Parse a .env file, stripping comments and inline comments."""
    result = {}
    if not os.path.exists(path):
        return result
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, raw_val = line.partition("=")
            key = key.strip()
            val = re.sub(r"\s+#.*$", "", raw_val).strip()
            result[key] = val
    return result


def is_placeholder(val: str) -> bool:
    """Return True if the value still looks like a placeholder."""
    placeholder_patterns = [
        r"^eyJ\.\.\.",
        r"^https://xxxx",
        r"^sk-\.\.\.",
        r"^sk-ant-\.\.\.",
        r"^xoxb-\.\.\.",
        r"^\.\.\.",
        r"^your-",
    ]
    return any(re.match(p, val) for p in placeholder_patterns)


def get_config_values() -> dict[str, str]:
    """
    Build the final key→value map.
    System env vars (Vercel) take priority over .env file (local dev).
    """
    # Start with .env file values (local dev fallback)
    env_file_vals = parse_env_file(ENV_FILE)

    result = {}
    for key in FRONTEND_KEYS:
        # 1. Check system environment first (Vercel injects these)
        sys_val = os.environ.get(key, "").strip()
        if sys_val and not is_placeholder(sys_val):
            result[key] = sys_val
            continue

        # 2. Fall back to .env file
        file_val = env_file_vals.get(key, "").strip()
        if file_val and not is_placeholder(file_val):
            result[key] = file_val
            continue

        # 3. Empty — app will run in demo mode
        result[key] = ""

    return result


def generate(values: dict[str, str]) -> str:
    """Build the config.js content."""
    lines = [
        "// config.js — AUTO-GENERATED by generate_config.py",
        "// DO NOT edit manually. DO NOT commit to git.",
        "// Re-run:  python generate_config.py",
        "",
    ]

    warnings = []
    for key in FRONTEND_KEYS:
        val = values.get(key, "")
        if not val:
            warnings.append(key)
        lines.append(f'window.{key} = "{val}";')

    lines.append("")

    if warnings:
        print("\nWARNING: The following keys are missing or placeholder:")
        for w in warnings:
            print(f"   - {w}")
        print("   The frontend will fall back to Demo Mode until you fill them in.\n")
    else:
        print("\nSUCCESS: config.js written — real Supabase credentials wired in.\n")

    return "\n".join(lines)


def main():
    values = get_config_values()
    content = generate(values)

    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"   config.js -> {CONFIG_FILE}")


if __name__ == "__main__":
    main()

